name: Publish all mmdb npm packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Create mmdb files
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to npm
        run: tools/publish-mmdb.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GTOKEN}}
          PUBLISH_ALL_MMDB: true
